-- ============================================================
-- KONEKT — Demo Seed Data (SQL Reference)
-- ============================================================
-- This is a standalone SQL file for manual import via phpMyAdmin
-- or MySQL CLI. It is the SQL equivalent of seed_demo.php.
--
-- IMPORTANT: Run this AFTER konekt_db.sql has been executed.
--
-- All demo users use password: Demo@12345
-- Bcrypt hash (cost 12): $2y$12$LJ3m4ysKQf8sX0Z0z8e5aOJ7x0z8e5aOJ7x0z8e5aOJ7x0z8e5a
-- NOTE: The PHP seeder generates a proper hash at runtime.
--       This SQL file uses a pre-computed hash for convenience.
--
-- To remove demo data:
--   DELETE FROM users WHERE email LIKE 'demo_%@konekt.test';
-- (CASCADE will clean up everything else)
-- ============================================================

USE konekt_db;

-- ============================================================
-- Pre-compute bcrypt hash for Demo@12345
-- We store it in a variable for reuse.
-- NOTE: MySQL doesn't natively support bcrypt. This hash was
-- generated by PHP's password_hash('Demo@12345', PASSWORD_BCRYPT).
-- If you need a fresh hash, run: php -r "echo password_hash('Demo@12345', PASSWORD_BCRYPT, ['cost'=>12]);"
-- ============================================================
SET @demo_pass = '$2y$12$wRQyO9fV6mKJ5qe3xU1Jf.W4SjzVxjY8Z2kNhL1mP7rT9uBvC3xGi';

-- ============================================================
-- 1. EMPLOYER ACCOUNTS
-- ============================================================
INSERT INTO users (email, password_hash, role, first_name, last_name) VALUES
    ('demo_maria@konekt.test', @demo_pass, 'employer', 'Maria', 'Santos'),
    ('demo_james@konekt.test', @demo_pass, 'employer', 'James', 'Reyes'),
    ('demo_anna@konekt.test',  @demo_pass, 'employer', 'Anna',  'Cruz');

SET @maria_id  = (SELECT id FROM users WHERE email = 'demo_maria@konekt.test');
SET @james_id  = (SELECT id FROM users WHERE email = 'demo_james@konekt.test');
SET @anna_id   = (SELECT id FROM users WHERE email = 'demo_anna@konekt.test');

-- Employer Profiles
INSERT INTO profiles (user_id, headline, bio, location, phone, industry, years_of_experience) VALUES
    (@maria_id, 'CEO & Founder at TechVault Philippines', 'Passionate about building the next generation of Filipino tech talent.', 'Makati City, Metro Manila', '+63 917 123 4567', 'Technology', 12),
    (@james_id, 'Managing Director at GreenField Agritech', 'Driving agricultural innovation through technology.', 'Los Baños, Laguna', '+63 918 234 5678', 'Agriculture', 8),
    (@anna_id,  'CTO at MediCare Solutions', 'Leading the digital health revolution in the Philippines.', 'Cebu City, Cebu', '+63 919 345 6789', 'Healthcare', 10);

-- ============================================================
-- 2. COMPANIES
-- ============================================================
INSERT INTO companies (user_id, name, description, industry, website, location, company_size, founded_year) VALUES
    (@maria_id, 'TechVault Philippines', 'Leading software development company specializing in enterprise solutions, cloud architecture, and digital transformation.', 'Technology', 'https://techvault.ph', 'Makati City, Metro Manila', '51-200', 2018),
    (@james_id, 'GreenField Agritech', 'Precision agriculture tools, drone-based crop monitoring, and data-driven solutions for Filipino farmers.', 'Agriculture', 'https://greenfield-agri.ph', 'Los Baños, Laguna', '11-50', 2020),
    (@anna_id,  'MediCare Solutions', 'Electronic health record systems, telemedicine platforms, and health informatics tools for hospitals and clinics.', 'Healthcare', 'https://medicare-solutions.ph', 'Cebu City, Cebu', '11-50', 2019);

SET @techvault_id  = (SELECT id FROM companies WHERE user_id = @maria_id);
SET @greenfield_id = (SELECT id FROM companies WHERE user_id = @james_id);
SET @medicare_id   = (SELECT id FROM companies WHERE user_id = @anna_id);

-- ============================================================
-- 3. JOB POSTINGS
-- ============================================================
SET @deadline = DATE_ADD(CURDATE(), INTERVAL 60 DAY);

-- TechVault Jobs
INSERT INTO job_postings (company_id, employer_id, title, description, requirements, responsibilities, location, job_type, work_arrangement, salary_min, salary_max, experience_level, min_experience_years, education_requirement, deadline) VALUES
    (@techvault_id, @maria_id, 'Full-Stack Web Developer',
     'We are looking for a talented Full-Stack Web Developer to join our growing engineering team.',
     '• 2+ years of experience in full-stack web development\n• Proficiency in PHP (Laravel preferred) and JavaScript\n• Experience with React or Vue.js',
     '• Build and maintain scalable web applications\n• Collaborate with UI/UX designers\n• Write clean, documented code',
     'Makati City, Metro Manila', 'full_time', 'hybrid', 35000, 55000, 'mid', 2, 'bachelors', @deadline),

    (@techvault_id, @maria_id, 'UI/UX Designer',
     'Join our creative team as a UI/UX Designer crafting intuitive, visually stunning interfaces.',
     '• Portfolio showcasing UI/UX projects\n• Proficiency in Figma and Adobe Creative Suite',
     '• Conduct user research and usability testing\n• Create wireframes, prototypes, and mockups',
     'Makati City, Metro Manila', 'full_time', 'hybrid', 30000, 50000, 'mid', 1, 'bachelors', @deadline),

    (@techvault_id, @maria_id, 'Data Analyst',
     'Seeking a Data Analyst to transform raw data into actionable business insights.',
     '• Strong SQL and Python skills\n• Experience with data visualization tools',
     '• Analyze large datasets to identify trends\n• Build and maintain interactive dashboards',
     'Makati City, Metro Manila', 'full_time', 'remote', 32000, 48000, 'entry', 1, 'bachelors', @deadline);

-- GreenField Jobs
INSERT INTO job_postings (company_id, employer_id, title, description, requirements, responsibilities, location, job_type, work_arrangement, salary_min, salary_max, experience_level, min_experience_years, education_requirement, deadline) VALUES
    (@greenfield_id, @james_id, 'Farm Systems Engineer',
     'Design and deploy IoT-based precision agriculture systems for Filipino farmers.',
     '• Background in agricultural engineering or IT\n• Experience with IoT devices\n• Python or C++ skills',
     '• Design and deploy smart farming sensor networks\n• Develop data collection pipelines',
     'Los Baños, Laguna', 'full_time', 'on_site', 28000, 42000, 'entry', 0, 'bachelors', @deadline),

    (@greenfield_id, @james_id, 'Agri-Data Scientist',
     'Build predictive models for crop health, analyze satellite imagery, and develop smart farming algorithms.',
     '• Degree in Data Science, Statistics, or Agriculture\n• Strong Python skills with ML libraries',
     '• Build predictive models for crop yield\n• Process satellite and drone imagery',
     'Los Baños, Laguna', 'full_time', 'hybrid', 35000, 55000, 'mid', 2, 'bachelors', @deadline),

    (@greenfield_id, @james_id, 'Agricultural Technology Intern',
     'Hands-on internship for students passionate about the intersection of technology and agriculture.',
     '• Currently enrolled or recently graduated\n• Basic computer literacy',
     '• Assist with drone-based crop monitoring\n• Collect and organize field sensor data',
     'Los Baños, Laguna', 'internship', 'on_site', 8000, 12000, 'entry', 0, 'none', @deadline);

-- MediCare Jobs
INSERT INTO job_postings (company_id, employer_id, title, description, requirements, responsibilities, location, job_type, work_arrangement, salary_min, salary_max, experience_level, min_experience_years, education_requirement, deadline) VALUES
    (@medicare_id, @anna_id, 'Health Informatics Specialist',
     'Help design and implement electronic health record (EHR) systems for hospitals across the Philippines.',
     '• Background in Health Informatics or IT\n• Familiarity with EHR/EMR systems\n• SQL skills',
     '• Configure and deploy EHR systems\n• Train medical staff on system usage',
     'Cebu City, Cebu', 'full_time', 'on_site', 30000, 45000, 'mid', 1, 'bachelors', @deadline),

    (@medicare_id, @anna_id, 'IT Support Lead',
     'Oversee technical operations at partner clinics, manage network infrastructure, and ensure uptime.',
     '• 2+ years IT support experience\n• Networking and cybersecurity knowledge\n• Linux proficiency',
     '• Manage network infrastructure\n• Implement cybersecurity policies',
     'Cebu City, Cebu', 'full_time', 'on_site', 28000, 40000, 'mid', 2, 'bachelors', @deadline);

-- ============================================================
-- 4. JOB SEEKER ACCOUNTS
-- ============================================================
INSERT INTO users (email, password_hash, role, first_name, last_name) VALUES
    ('demo_carlo@konekt.test',    @demo_pass, 'job_seeker', 'Carlo',    'Mendoza'),
    ('demo_sofia@konekt.test',    @demo_pass, 'job_seeker', 'Sofia',    'Garcia'),
    ('demo_miguel@konekt.test',   @demo_pass, 'job_seeker', 'Miguel',   'Torres'),
    ('demo_isabella@konekt.test', @demo_pass, 'job_seeker', 'Isabella', 'Ramos'),
    ('demo_rafael@konekt.test',   @demo_pass, 'job_seeker', 'Rafael',   'Lim');

SET @carlo_id    = (SELECT id FROM users WHERE email = 'demo_carlo@konekt.test');
SET @sofia_id    = (SELECT id FROM users WHERE email = 'demo_sofia@konekt.test');
SET @miguel_id   = (SELECT id FROM users WHERE email = 'demo_miguel@konekt.test');
SET @isabella_id = (SELECT id FROM users WHERE email = 'demo_isabella@konekt.test');
SET @rafael_id   = (SELECT id FROM users WHERE email = 'demo_rafael@konekt.test');

-- Job Seeker Profiles
INSERT INTO profiles (user_id, headline, bio, location, phone, industry, years_of_experience) VALUES
    (@carlo_id,    'Full-Stack Web Developer',   'Passionate developer with 3 years of experience building web apps with PHP, Laravel, and React.', 'Quezon City, Metro Manila', '+63 920 111 2233', 'Technology', 3),
    (@sofia_id,    'UX Designer & Researcher',   'Creative UX designer with a keen eye for detail. Great design starts with understanding people.', 'Taguig City, Metro Manila', '+63 921 222 3344', 'Design', 2),
    (@miguel_id,   'Data Science Enthusiast',    'Recent graduate passionate about machine learning and data analytics.', 'Manila, Metro Manila', '+63 922 333 4455', 'Technology', 1),
    (@isabella_id, 'IT Support Specialist',      'Detail-oriented IT professional with network administration and cybersecurity experience.', 'Cebu City, Cebu', '+63 923 444 5566', 'Technology', 4),
    (@rafael_id,   'Agricultural Technologist',  'Bridging technology and agriculture. Experienced in GIS mapping and drone operations.', 'Los Baños, Laguna', '+63 924 555 6677', 'Agriculture', 2);

-- ============================================================
-- 5. CONNECTIONS
-- ============================================================
INSERT INTO connections (requester_id, receiver_id, status, message) VALUES
    (@carlo_id,    @sofia_id,  'accepted', 'Hey Sofia! Saw your portfolio — amazing work. Let''s connect!'),
    (@miguel_id,   @carlo_id,  'accepted', 'Hi Carlo, I''m interested in data-driven web apps. Would love to chat!'),
    (@sofia_id,    @miguel_id, 'accepted', 'Hi Miguel! I''m designing dashboards and need data insights — let''s connect.'),
    (@rafael_id,   @miguel_id, 'accepted', 'Hey Miguel, fellow data enthusiast here but in agriculture. Let''s share ideas!'),
    (@isabella_id, @carlo_id,  'pending',  'Hi Carlo! I''m looking to transition into web development. Would love your advice.');

-- ============================================================
-- 6. REMOVAL COMMAND
-- ============================================================
-- To remove all demo data, simply run:
--   DELETE FROM users WHERE email LIKE 'demo_%@konekt.test';
-- All related data will be cascade-deleted automatically.
